spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    cache: false
  application:
    name: service-desc
  datasource:
    url: jdbc:postgresql://localhost:5439/camunda_test?currentSchema=sd_schema
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: sd_schema

security:
  jwt:
    secret: ZnVtb2Z1bW9mdW1vZnVtb2Z1bW9mdW1vZnVtbw==
    access: 1
    refresh: 30

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P1D
    admin_user:
      id: admin
      password: admin
      first-name: admin
      last-name: admin